Minor revisions to ```simulation.py```
maximenc/pycop pull request #2
Opened 2022-07-09 21:46 UTC by David-Woroniuk

- Typechecks
- Type Annotation

Removed：

- Non CamelCase Class Names (PEP:8)
- CamelCase local varibales within functions (should be snakecase PEP:8)

2022-08-04 17:43 UTC, maximenc requested changes
Seems that there are type errors when checking the modification in _simulation.py_. The issue is resolved when considering _np.ndarray_ and the possibility of a variable being _int_ or _float_ when testing the type (in _isinstance()_).

Some minor changes would be required in the simulation section of the readme file, especially to change the matrix variable as a numpy array.

2022-08-04 17:43 UTC, maximenc commented on pycop/simulation.py
> +    if not isinstance(corr_matrix, np.array):
Seems that for checking the type we need provide "np.ndarray" and not "np.array":
```suggestion
    if not isinstance(corr_matrix, np.ndarray):
```

2022-08-04 17:43 UTC, maximenc commented on pycop/simulation.py
> +    if not isinstance(corr_matrix, np.array):
```suggestion
    if not isinstance(corr_matrix, np.ndarray):
```

2022-08-04 17:43 UTC, maximenc commented on pycop/simulation.py
> +    if not isinstance(nu, float):
I would consider the possibility that the variable is passed as an integer in the following:
```suggestion
    if not isinstance(nu, (int, float)):
```
For the typing, it seems that we can use _float_ only, as _int_ is implied in that type.

2022-08-04 17:43 UTC, maximenc commented on pycop/simulation.py
> +    if not isinstance(alpha, float):
```suggestion
    if not isinstance(alpha, (int, float)):
```

2022-08-04 17:43 UTC, maximenc commented on pycop/simulation.py
> +    if not isinstance(theta, float):
```suggestion
    if not isinstance(theta, (int, float)):
```

2022-08-25 13:23 UTC, David-Woroniuk commented
Hey @maximenc - I agree with each of the above, I was unsure of the ```nu``` value as an ```int``` type. I think this should be ready to merge, assuming it passes unit tests.

2022-08-25 13:34 UTC, merged